# Generated by Django 4.2.7 on 2025-07-21 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('ug_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('ug_college', models.CharField(blank=True, max_length=255, null=True)),
                ('ug_year', models.IntegerField(blank=True, null=True)),
                ('pg_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_college', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_year', models.IntegerField(blank=True, null=True)),
                ('total_experience_years', models.IntegerField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('raw_resume', models.BinaryField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
    ]
