# Generated by Django 4.2.7 on 2025-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_resume_total_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
